"""Controlled tools for the spdb_power_finance compute and policy corpus.

This module deliberately does not ask an LLM to write SQL. Each supported
question maps to a parameter-free query template after the facility code and
year have been resolved from database-owned values. That keeps the structured
facts, policy evidence and finance boundaries auditable.
"""

from __future__ import annotations

import csv
import re
import subprocess
from dataclasses import dataclass
from io import StringIO
from typing import Any, Protocol

from .config import Settings


@dataclass(frozen=True)
class QueryResult:
    columns: list[str]
    rows: list[list[str]]


class QueryRunner(Protocol):
    def execute(self, sql: str) -> QueryResult: ...


class SpdbReadOnlyRunner:
    """Executes only SQL generated by this module using an encrypted login path."""

    def __init__(self, settings: Settings) -> None:
        self.settings = settings

    def execute(self, sql: str) -> QueryResult:
        completed = subprocess.run(
            [
                str(self.settings.mysql_binary),
                f"--login-path={self.settings.spdb_sql_login_path}",
                "--default-character-set=utf8mb4",
                "--batch",
                "--raw",
                self.settings.spdb_database,
                "-e",
                sql,
            ],
            capture_output=True,
            text=True,
            timeout=10,
            check=False,
        )
        if completed.returncode:
            raise RuntimeError(completed.stderr.strip() or "spdb_power_finance 查询失败。")
        if not completed.stdout.strip():
            return QueryResult([], [])
        parsed = list(csv.reader(StringIO(completed.stdout), delimiter="\t"))
        return QueryResult(parsed[0], parsed[1:])


def _row_as_dict(result: QueryResult, row: list[str]) -> dict[str, str]:
    return dict(zip(result.columns, row, strict=True))


def _as_percent(value: str | None) -> str:
    if value in {None, "", "NULL"}:
        return "未披露"
    return f"{float(value) * 100:.2f}%"


def _as_yuan(value: str | None, digits: int = 2) -> str:
    if value in {None, "", "NULL"}:
        return "未披露"
    return f"{float(value):,.{digits}f} 元"


class EnergyComputeAgent:
    """Tool router for the present V0.2 catalogue.

    It owns only the compute/power-policy domain. Questions outside that domain
    are delegated by ``HybridAgent`` to unchanged BankAI V0.4.
    """

    _COMPUTE_TERMS = (
        "百旺信", "智算", "算力", "数据中心", "机柜", "上架率", "训力券",
        "绿色贷款", "绿色金融", "绿色数据中心", "pue", "dscr", "可贷", "融资比例",
    )
    _FINANCE_TERMS = ("绿色贷款", "绿色金融", "贷款比例", "可贷比例", "融资比例", "dscr", "融资")
    _POLICY_TERMS = ("训力券", "政策", "补贴", "资格", "直接收入", "绿色金融", "绿色贷款")
    _FACILITY_TERMS = ("上架率", "机柜", "托管", "pue", "运营", "电价", "容量", "投资")
    _SAFE_FACILITY_CODE = re.compile(r"^[A-Z0-9_-]{1,32}$")
    _YEAR = re.compile(r"(?<!\d)(20\d{2})(?!\d)")
    _GENERIC_NAME_FRAGMENTS = {
        "数据中心", "智算中心", "服务器", "托管", "机房", "项目", "三期", "一期", "二期",
    }

    def __init__(self, settings: Settings, runner: QueryRunner | None = None) -> None:
        self.settings = settings
        self.runner = runner or SpdbReadOnlyRunner(settings)

    @classmethod
    def supports(cls, question: str) -> bool:
        lowered = question.lower()
        return any(term in lowered for term in cls._COMPUTE_TERMS)

    def run(self, question: str) -> dict[str, Any]:
        if not question.strip():
            raise ValueError("问题不能为空。")
        route = self._route(question)
        if route == "SQL":
            return self._facility_operation_answer(question)
        if route == "RAG":
            return self._policy_answer(question)
        return self._finance_analysis(question)

    def _route(self, question: str) -> str:
        lowered = question.lower()
        if any(term in lowered for term in self._FINANCE_TERMS):
            return "BOTH"
        if any(term in lowered for term in self._POLICY_TERMS) and not any(
            term in lowered for term in self._FACILITY_TERMS
        ):
            return "RAG"
        return "SQL"

    def _facility(self, question: str) -> dict[str, str] | None:
        facilities = self.runner.execute(
            "SELECT facility_code,official_name,facility_alias FROM enterprise_data_center_v2 "
            "ORDER BY facility_code"
        )
        lowered = question.lower()
        best: dict[str, str] | None = None
        best_length = 0
        for row in facilities.rows:
            item = _row_as_dict(facilities, row)
            names = [item.get("facility_code", ""), item.get("official_name", "")]
            names.extend(re.split(r"[；;、,，]", item.get("facility_alias") or ""))
            for name in names:
                normalized = name.strip().lower()
                match_length = self._facility_name_match_length(normalized, lowered)
                if match_length > best_length:
                    best, best_length = item, match_length
        return best

    @classmethod
    def _facility_name_match_length(cls, candidate: str, question: str) -> int:
        """Match a stable facility-name fragment without accepting generic words.

        Public questions often use a company shorthand such as ``百旺信`` while
        the database stores the formal facility name.  A three-character,
        non-generic common substring is sufficient for that controlled
        shorthand; city names (typically two characters) and generic words are
        explicitly rejected so they cannot silently select an arbitrary site.
        """

        if len(candidate) < 3:
            return 0
        if candidate in question:
            return len(candidate)
        best = 0
        for start in range(len(candidate)):
            for end in range(start + 3, len(candidate) + 1):
                fragment = candidate[start:end]
                if fragment in cls._GENERIC_NAME_FRAGMENTS or fragment not in question:
                    continue
                best = max(best, len(fragment))
        return best

    def _facility_code(self, question: str) -> tuple[str | None, str | None]:
        facility = self._facility(question)
        if not facility:
            return None, None
        code = facility["facility_code"]
        if not self._SAFE_FACILITY_CODE.fullmatch(code):
            raise RuntimeError("设施代码未通过受控查询校验。")
        return code, facility["official_name"]

    def _year(self, question: str) -> int | None:
        match = self._YEAR.search(question)
        return int(match.group(1)) if match else None

    def _facility_operation_answer(self, question: str) -> dict[str, Any]:
        code, official_name = self._facility_code(question)
        if not code:
            return self._unsupported_sql(question, "未识别到已入库的算力设施名称，不能猜测数据库数值。")
        year = self._year(question)
        year_clause = f"AND o.fact_year={year}" if year else ""
        operation = self.runner.execute(
            "SELECT f.official_name,o.operation_scope_name,o.fact_year,o.fact_period,"
            "o.rack_capacity_count,o.average_occupied_rack_count,o.rack_utilization_ratio,"
            "o.average_rack_price_yuan_month,ds.source_title,ds.source_url,o.source_locator "
            "FROM compute_facility_operation_fact_v1 o "
            "JOIN enterprise_data_center_v2 f ON f.facility_v2_id=o.facility_v2_id "
            "JOIN data_source ds ON ds.source_id=o.source_id "
            f"WHERE f.facility_code='{code}' "
            "AND o.operation_scope_code='WHOLE_FACILITY_BUILDING_1_4_SELF_BUILT' "
            f"{year_clause} ORDER BY o.fact_year DESC,o.fact_period DESC LIMIT 1"
        )
        if not operation.rows:
            period = f"{year} 年" if year else "当前"
            return self._unsupported_sql(question, f"数据库没有 {official_name} {period} 的整体运营事实，不能补造上架率或机柜价格。")
        fact = _row_as_dict(operation, operation.rows[0])
        answer = (
            f"{fact['official_name']}在 {fact['fact_year']} 年{fact['fact_period']}、"
            f"“{fact['operation_scope_name']}”口径下，上架率为 {_as_percent(fact['rack_utilization_ratio'])}，"
            f"平均机柜价格为 {_as_yuan(fact['average_rack_price_yuan_month'])}/柜/月。"
            "该口径为1栋与4栋自建服务器托管运营整体，不能解释为三期项目的独立经营指标。"
        )
        source = self._sql_source(fact)
        return {
            "agent_version": "EnergyComputeAI-V0.2",
            "question": question.strip(),
            "route": "SQL",
            "router": {"route": "SQL", "reason": "命中已入库算力设施运营指标。"},
            "decomposition": None,
            "tool_calls": [{"order": 1, "tool": "SPDB_SQL_CATALOG", "catalog": "FACILITY_OPERATION_FACT"}],
            "sql_result": {"query_result": {"columns": operation.columns, "rows": operation.rows}},
            "rag_result": None,
            "synthesis": None,
            "sources": [source],
            "final_answer": answer,
        }

    def _policy_answer(self, question: str) -> dict[str, Any]:
        rules = self._policy_rules(question)
        if not rules.rows:
            return self._policy_insufficient(question)
        records = [_row_as_dict(rules, row) for row in rules.rows]
        is_voucher = "训力券" in question
        if is_voucher:
            answer = (
                "不能仅凭深圳训力券政策将其认定为算力服务商的直接收入。"
                "当前规则明确的是需求方购买非关联智能算力后可申请抵扣；服务机构入库是供给资格，"
                "并且申请方不能同时取得服务机构入库资格和申领训力券。"
                "对服务商而言，只有在服务合同、交付、结算与收入确认资料均完备时，才能另行判断实际业务收入；"
                "政策补贴本身不应自动计入服务商收入或融资现金流。"
            )
        else:
            answer = "已检索到与问题相关的政策原子规则。结论仅限于下列原文摘录和适用条件，最终资格仍需人工核验。"
        references = [self._policy_reference(record) for record in records]
        claims = [
            {"claim_type": "RAG_EVIDENCE", "text": record["requirement_summary"], "support_ids": [f"R{index}"]}
            for index, record in enumerate(records, start=1)
        ]
        return {
            "agent_version": "EnergyComputeAI-V0.2",
            "question": question.strip(),
            "route": "RAG",
            "router": {"route": "RAG", "reason": "命中政策资格或支持规则问题。"},
            "decomposition": None,
            "tool_calls": [{"order": 1, "tool": "SPDB_POLICY_RETRIEVAL", "rule_count": len(records)}],
            "sql_result": None,
            "rag_result": {"answerable": True, "references": references},
            "synthesis": {"claims": claims, "dropped_claims": []},
            "sources": references,
            "final_answer": answer,
        }

    def _finance_analysis(self, question: str) -> dict[str, Any]:
        code, official_name = self._facility_code(question)
        if not code:
            return self._unsupported_sql(question, "未识别到已入库设施，不能开展项目融资初步判断。", route="BOTH")
        cashflows = self.runner.execute(
            "SELECT scenario_code,scenario_name,reference_historical_capex_yuan,reference_pue,"
            "year1_rack_occupancy_ratio,steady_state_rack_occupancy_ratio,year1_pre_tax_cashflow_proxy_yuan,"
            "hypothetical_greenfield_npv_proxy_yuan,result_status,assumption_note "
            "FROM v_compute_facility_project_cashflow_summary_v1 "
            f"WHERE facility_code='{code}' ORDER BY scenario_code"
        )
        due_diligence = self.runner.execute(
            "SELECT check_code,check_name,evidence_status,risk_level,evidence_summary,required_evidence,due_diligence_action "
            "FROM v_compute_facility_project_due_diligence_v1 "
            f"WHERE facility_code='{code}' AND project_scope_code='PHASE_III_EXCHANGE_DISCLOSURE' "
            "ORDER BY sort_order"
        )
        policy_rules = self._policy_rules("绿色贷款 绿色数据中心")
        policy_records = [_row_as_dict(policy_rules, row) for row in policy_rules.rows]
        blockers = [
            _row_as_dict(due_diligence, row)
            for row in due_diligence.rows
            if _row_as_dict(due_diligence, row).get("evidence_status") in {"PENDING", "PARTIAL"}
        ]
        finance_status = "INSUFFICIENT_INPUT" if blockers else "READY_FOR_RULE_CALCULATION"
        warning = (
            "三期项目尚缺独立收入、成本、税费、营运资本、维护CAPEX、债务本息和现金流量表；"
            "现有结果仅为税前经营现金流代理，不能计算或承诺贷款比例。"
            if blockers
            else "可进入规则化DSCR测算，仍须以项目级财务和合同材料复核。"
        )
        answer = (
            f"{official_name}可作为绿色金融初筛和项目尽调对象，但目前不能给出可贷比例。"
            "绿色数据中心目录要求资金用途对应建设或改造，并满足GB 40879二级能效水平及金融机构尽调要求；"
            f"当前融资工具状态为 {finance_status}。{warning}"
            "历史投资额、园区整体上架率或研究情景NPV都不能替代项目级CFADS。"
        )
        finance_data = {
            "status": finance_status,
            "formula": "可承受贷款额 = min(政策上限、DSCR容量) × 合格CAPEX；DSCR = CFADS / 当期本息偿付额。",
            "missing_evidence": [item["required_evidence"] for item in blockers],
        }
        sources = [self._policy_reference(record) for record in policy_records]
        claims = [
            {
                "claim_type": "RAG_EVIDENCE",
                "text": record["requirement_summary"],
                "support_ids": [f"R{index}"],
            }
            for index, record in enumerate(policy_records, start=1)
        ]
        return {
            "agent_version": "EnergyComputeAI-V0.2",
            "question": question.strip(),
            "route": "BOTH",
            "router": {"route": "BOTH", "reason": "同时命中设施事实、绿色金融规则和融资测算问题。"},
            "decomposition": {
                "sql_fact_question": "读取项目现金流情景和尽调状态。",
                "rag_policy_question": "检索绿色数据中心和绿色金融目录条件。",
                "hard_constraints": ["不将研究情景解释为授信结论", "CFADS缺失时拒绝计算可贷比例"],
            },
            "tool_calls": [
                {"order": 1, "tool": "SPDB_SQL_CATALOG", "catalog": "FACILITY_CASHFLOW_AND_DUE_DILIGENCE"},
                {"order": 2, "tool": "SPDB_POLICY_RETRIEVAL", "rule_count": len(policy_records)},
                {"order": 3, "tool": "FINANCE_RULE_ENGINE", "status": finance_status},
            ],
            "sql_result": {"query_result": {"columns": cashflows.columns, "rows": cashflows.rows}},
            "rag_result": {"answerable": bool(policy_records), "references": sources},
            "synthesis": {"claims": claims, "dropped_claims": []},
            "sources": sources,
            "finance_result": finance_data,
            "final_answer": answer,
        }

    def _policy_rules(self, question: str) -> QueryResult:
        categories: tuple[str, ...]
        if "训力券" in question:
            categories = ("COMPUTE_VOUCHER",)
        elif any(term in question for term in ("绿色贷款", "绿色金融", "绿色数据中心")):
            categories = ("GREEN_FINANCE", "GREEN_DATA_CENTER")
        else:
            categories = ("COMPUTE_INFRASTRUCTURE", "COMPUTE_ENERGY_SYNERGY")
        category_sql = ",".join(f"'{category}'" for category in categories)
        return self.runner.execute(
            "SELECT d.file_name,d.document_title,d.policy_level,d.official_url,"
            "r.rule_code,r.rule_title,r.applicability_summary,r.requirement_summary,"
            "r.required_evidence,r.source_locator,r.model_impact_type "
            "FROM policy_rule_v1 r JOIN policy_document_v1 d ON d.policy_document_id=r.policy_document_id "
            f"WHERE d.policy_category IN ({category_sql}) "
            "AND d.policy_status IN ('EFFECTIVE','APPLICATION_CLOSED','REFERENCE') "
            "AND r.rule_status <> 'INVALID' "
            "ORDER BY CASE WHEN r.rule_code='NAT_GREEN_FINANCE_2025_GREEN_DC' THEN 0 ELSE 1 END, "
            "d.policy_level,r.policy_rule_id LIMIT 5"
        )

    @staticmethod
    def _sql_source(fact: dict[str, str]) -> dict[str, Any]:
        return {
            "source_filename": fact.get("source_title") or "数据库经营事实来源",
            "title": fact.get("source_title"),
            "authority_code": "PUBLIC_DISCLOSURE",
            "supporting_quote": (
                f"{fact.get('operation_scope_name')}：{fact.get('fact_year')}年"
                f"上架率{_as_percent(fact.get('rack_utilization_ratio'))}，"
                f"平均机柜价格{_as_yuan(fact.get('average_rack_price_yuan_month'))}/柜/月。"
            ),
            "source_locator": fact.get("source_locator"),
            "official_url": fact.get("source_url"),
        }

    @staticmethod
    def _policy_reference(record: dict[str, str]) -> dict[str, Any]:
        return {
            "source_filename": record["file_name"],
            "title": record["document_title"],
            "authority_code": record["policy_level"],
            "supporting_quote": record["requirement_summary"],
            "source_locator": record.get("source_locator"),
            "official_url": record.get("official_url"),
        }

    def _unsupported_sql(self, question: str, message: str, route: str = "SQL") -> dict[str, Any]:
        return {
            "agent_version": "EnergyComputeAI-V0.2",
            "question": question.strip(),
            "route": route,
            "router": {"route": route, "reason": "结构化数据未命中，拒绝猜测。"},
            "decomposition": None,
            "tool_calls": [{"order": 1, "tool": "SPDB_SQL_CATALOG", "status": "NO_MATCH"}],
            "sql_result": None,
            "rag_result": None,
            "synthesis": {"claims": [], "dropped_claims": []},
            "sources": [],
            "final_answer": message,
        }

    def _policy_insufficient(self, question: str) -> dict[str, Any]:
        return {
            "agent_version": "EnergyComputeAI-V0.2",
            "question": question.strip(),
            "route": "RAG",
            "router": {"route": "RAG", "reason": "政策问题，但未检索到可用规则。"},
            "decomposition": None,
            "tool_calls": [{"order": 1, "tool": "SPDB_POLICY_RETRIEVAL", "rule_count": 0}],
            "sql_result": None,
            "rag_result": {"answerable": False, "references": [], "insufficiency_reason": "当前政策规则库未返回可核验依据。"},
            "synthesis": {"claims": [], "dropped_claims": []},
            "sources": [],
            "final_answer": "根据当前政策规则库，无法确定该问题；请补充具体政策文件或业务主体。",
        }
